// Generated by CoffeeScript 1.7.1
(function() {
  var app, express;

  express = require('express');

  app = express();

  app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "http://localhost:63342");
    res.header("Access-Control-Allow-Methods", "GET,PUT,POST,DELETE,OPTIONS");
    res.header("Access-Control-Allow-Headers", "X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept");
    next();
  });

  app.get('/', function(req, res) {
    return res.json({
      message: "Hopefully you see this"
    });
  });

  app.listen(4000);

}).call(this);

//# sourceMappingURL=app.map
